.PHONY: build clean

build-movie:
	#Directory, File: Default Test (BlueRay)
	mkdir -p ~/TFG/testlibrary/'Sisters.And.Brothers.2011.1080p.BluRay.H264.AAC-RARBG'
	touch ~/TFG/testlibrary/'Sisters.And.Brothers.2011.1080p.BluRay.H264.AAC-RARBG'/'Sisters.And.Brothers.2011.1080p.BluRay.H264.AAC-RARBG.mkv'
	
	#Directory, File: Default Test
	mkdir -p ~/TFG/testlibrary/'Innocent.Bystanders.1972.BRRip.XviD.MP3-RARBG'
	touch ~/TFG/testlibrary/'Innocent.Bystanders.1972.BRRip.XviD.MP3-RARBG'/'Innocent.Bystanders.1972.BRRip.XviD.MP3-RARBG.mkv'
	
	#Directory, File: Default Test (Dates)
	mkdir -p ~/TFG/testlibrary/'Meet.Him.And.Die.1976.1080p.BluRay.H264.AAC-RARBG'
	touch ~/TFG/testlibrary/'Meet.Him.And.Die.1976.1080p.BluRay.H264.AAC-RARBG'/'Meet.Him.And.Die.1976.1080p.BluRay.H264.AAC-RARBG.mkv'
	
	#Directory, Subdirectory, File: Default Test (Mp3)
	mkdir -p ~/TFG/testlibrary/'Littlerock.2010.BRRip.XviD.MP3-RARBG'
	mkdir -p ~/TFG/testlibrary/'Littlerock.2010.BRRip.XviD.MP3-RARBG'/'subs'
	mkdir -p ~/TFG/testlibrary/'Littlerock.2010.BRRip.XviD.MP3-RARBG'/'sub'
	touch ~/TFG/testlibrary/'Littlerock.2010.BRRip.XviD.MP3-RARBG'/'sub'/'Littlerock.2010(english).str'
	touch ~/TFG/testlibrary/'Littlerock.2010.BRRip.XviD.MP3-RARBG'/'Littlerock.2010.BRRip.XviD.MP3-RARBG.mkv'
	
	#Directory, Subdirectory, File: Default Test (EXTENDED.CUT,BRRip, XviD)
	mkdir -p ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'
	mkdir -p ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'sub'
	touch ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'sub'/'Were.the.Millers.2013(english).str'
	touch ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'System.nfo'
	touch ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'Readme.txt'
	touch ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'RARBG.mkv'
	touch ~/TFG/testlibrary/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG'/'Were.the.Millers.2013.EXTENDED.CUT.BRRip.XviD.MP3-RARBG.mkv'

	#Directory, File: Unkonw Movie
	#mkdir -p ~/TFG/testlibrary/'Lost.Kiddo.The.Movie.(1080p).(2015)'
	#touch ~/TFG/testlibrary/'Lost.Kiddo.The.Movie.(1080p).(2015)'/'Lost.Kiddo.The.Movie.(1080p).(2015).mkv'

build-serie:
	#Directory, File: Default Test
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones.S06.1080p.BluRay.x264-ROVERS[rartv]'
	touch ~/TFG/testlibrary/'Game.of.Thrones.S06.1080p.BluRay.x264-ROVERS[rartv]'/'Game.of.Thrones.S06E01.1080p.BluRay.x264-ROVERS[rartv].mkv'
	touch ~/TFG/testlibrary/'Game.of.Thrones.S06.1080p.BluRay.x264-ROVERS[rartv]'/'Game.of.Thrones.S06E02.1080p.BluRay.x264-ROVERS[rartv].mkv'
	touch ~/TFG/testlibrary/'Game.of.Thrones.S06.1080p.BluRay.x264-ROVERS[rartv]'/'Game.of.Thrones.S06E03.1080p.BluRay.x264-ROVERS[rartv].mkv'
	
	#Directory, Subdirectory, File: Default Test
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones-season2'/
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones.season-3'/
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E01.1080p.BluRay.x265-PODO[rartv]'/
	touch ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E01.1080p.BluRay.x265-PODO[rartv]'/'Game.Of.Thrones.S01E01.1080p.mkv'
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E02.1080p.BluRay.x265-PODO[rartv]'/
	touch ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E02.1080p.BluRay.x265-PODO[rartv]'/'Game.Of.Thrones.S01E02.1080p.mkv'
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E03.1080p.BluRay.x265-PODO[rartv]'/
	touch ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E03.1080p.BluRay.x265-PODO[rartv]'/'Game.Of.Thrones.S01E03.1080p.mkv'
	mkdir -p ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E03.1080p.BluRay.x265-PODO[rartv]'/'subtitles'
	touch ~/TFG/testlibrary/'Game.of.Thrones [Season 1]'/'Game.Of.Thrones.S01E03.1080p.BluRay.x265-PODO[rartv]'/'subtitles'/'Game.Of.Thrones.s01.e03(english).str'
	
	#Directory, File: Retrieving Lost Episode Test
	mkdir -p ~/TFG/testlibrary/'Game.Of.Thrones.S01E05.1080p.BluRay.x265-PODO[rartv]'/
	touch ~/TFG/testlibrary/'Game.Of.Thrones.S01E05.1080p.BluRay.x265-PODO[rartv]'/'Game.Of.Thrones.S01E05.1080p.mkv'
	mkdir -p ~/TFG/testlibrary/'Game.Of.Thrones.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'
	touch ~/TFG/testlibrary/'Game.Of.Thrones.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'/'Game.Of.Thrones.S01.E05(english).str'
	touch ~/TFG/testlibrary/'Game.Of.Thrones.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'/'Game.Of.Thrones.S01.E05(es).str'

	#Directory, File: Default
	mkdir -p ~/TFG/testlibrary/'Teen.Wolf.S01E05.1080p.BluRay.x265-PODO[rartv]'/
	touch ~/TFG/testlibrary/'Teen.Wolf.S01E05.1080p.BluRay.x265-PODO[rartv]'/'Teen.Wolf.S01E05.1080p.mkv'
	mkdir -p ~/TFG/testlibrary/'Teen.Wolf.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'
	touch ~/TFG/testlibrary/'Teen.Wolf.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'/'Teen.Wolf.S01.E05(english).str'
	touch ~/TFG/testlibrary/'Teen.Wolf.S01E05.1080p.BluRay.x265-PODO[rartv]'/'subtitles'/'Teen.Wolf.S01.E05(es).str'

	#Directory, File: Retrieving Repetead Lost Episode Test
	#mkdir -p ~/TFG/testlibrary/'Game.Of.Thrones.S01E01.1080p.BluRay.x265-PODO[rartv]'/'Game.Of.Thrones.S01E01.1080p.mkv'
	
	#Directory, Subdirectory, File: Unkonwn Show
	#mkdir -p ~/TFG/testlibrary/'Krystal-The.Black Stripper-S02E01-The.dAy.0f.7he stripper.720p[rartv]'
	#touch ~/TFG/testlibrary/'Krystal-The.Black Stripper-S02E01-The.dAy.0f.7he stripper.720p[rartv]'/'System.nfo'
	#touch ~/TFG/testlibrary/'Krystal-The.Black Stripper-S02E01-The.dAy.0f.7he stripper.720p[rartv]'/'rartv.txt'
	#mkdir -p ~/TFG/testlibrary/'Krystal-The.Black Stripper-S02E01-The.dAy.0f.7he stripper.720p[rartv]'/'sub'
	#touch ~/TFG/testlibrary/'Krystal-The.Black Stripper-S02E01-The.dAy.0f.7he stripper.720p[rartv]'/'sub'/'Krystal-The.Black Stripper-S02E01(es).str'
	
#build-chaos:

build-all:
	make build-movie
	make build-serie
	#build-chaos

clean:
	rm -rf ~/TFG/testlibrary/*
